### PR TITLE
feat: get built-in packages

### LINKED ISSUE #133: Can not find com.unity.postprocessing@14.0.9 via CLI
_Originally posted by @from2001 in https://github.com/openupm/openupm-cli/issues/19#issuecomment-1871057403_
            

> I think this bug still remains with some packages. 
> 
> It is OK for com.unity.postprocessing, but this bug still happens with com.unity.render-pipelines.universal
> 
> The latest version of com.unity.render-pipelines.universal is now 14.0.9, however, 
> 
> `openupm add com.unity.render-pipelines.universal@14.0.1` outputs the error, and maximum version which can be installed is 10.10.1
> ```
> WARN 404 version 14.0.1 is not a valid choice of: 7.0.0, 7.0.1, 7.1.1, 7.1.2, 7.1.5, 7.1.6, 7.1.7, 7.1.8, 7.2.0, 7.2.1, 8.0.1, 7.3.1, 9.0.0-preview.14, 8.1.0, 7.4.1, 9.0.0-preview.35, 8.2.0, 10.0.0-preview.26, 7.4.2, 7.4.3, 9.0.0-preview.55, 7.5.1, 10.1.0, 9.0.0-preview.72, 10.2.0, 8.3.1, 10.2.1, 7.5.2, 10.2.2, 10.3.1, 7.5.3, 10.3.2, 10.4.0, 7.6.0, 10.5.0, 7.7.0, 10.5.1, 10.6.0, 7.7.1, 10.7.0, 10.8.0, 10.8.1, 10.9.0, 10.10.0, 10.10.1
> ```
> 
> Because of this, I cannot add dependencies which requires com.unity.render-pipelines.universal 14.0.1 such as 
> com.unity.polyspatial@0.7.1 in my package.
> 
> Please take a look. I will use -f option until this bug fixes.
> 
> Thank you for the great service, anyway.
> Best
>

### PR DESCRIPTION
**Pull request by ComradeVanti**
Built-in packages require special logic when validating versions/dependencies. Currently we manually keep a list of internal/built-in packages in order to determine if a package is built-in. This is brittle since what packages are internal changes for different editor-versions, as can be seen in #133.

This PR adds a function for loading the names of all built-in packages for an installed Unity editor. This could be used to more robustly check if a package is built-in. This could then be used to fix #133 and related issues.

### CODE REVIEW

**Comment by ComradeVanti** [comment]
@favoyang I am curious what you think about this approach :)

**Comment by ComradeVanti** [comment]
A note on this: the path of the Unity installation is assumed to be the default install-location. In order to support manually configured install-locations we could add a cmd-option.

**Comment by favoyang** [comment]
> @favoyang I am curious what you think about this approach :)

I agree with this approach. I will give a review tomorrow.

**Comment by favoyang** [comment]
> A note on this: the path of the Unity installation is assumed to be the default install-location. In order to support manually configured install-locations we could add a cmd-option.

Agree.

**Review by favoyang — APPROVED** [review]

**Comment by ComradeVanti** [comment]
@favoyang is it a problem if I merge this PR with `feat`?

**Comment by favoyang** [comment]
It's okay if you want to trigger a new version.

**Comment by favoyang** [comment]
> It's okay if you want to trigger a new version.

Notice that this squashed commit message is "refactor:...", it won't trigger a release.

[refactor: get built-in packages (](https://github.com/openupm/openupm-cli/commit/0e7bf81af8f437c7fd6e0edff2e4789cc4941004)https://github.com/openupm/openupm-cli/pull/225[)](https://github.com/openupm/openupm-cli/commit/0e7bf81af8f437c7fd6e0edff2e4789cc4941004)

**Comment by ComradeVanti** [comment]
This was on purpose. I did not want a release, because this PR does not add any new behavior that is observable to users. In that sense it is kind of in the middle between a feature and a refactor. I wasn't sure which term to use for that.

**Pull request merged**
