### PR TITLE
refactor: rename package / manifest types

### PR DESCRIPTION
**Pull request by ComradeVanti**
Rename and refactor types related to Unity packages / packuments.

Affected types are:

- `PkgInfo` ➡️ `UnityPackument`
- `PkgVersionInfo` ➡️ `UnityPackumentVersion`
- `PkgManifest` ➡️ `UnityProjectManifest`
- ➕ `UnityPackageManifest`

Variable-, function-, file- and test-names were also updated accordingly.

This is done mainly for two reasons:

- Use common npm terms for the Unity equivalent
- Disambiguate package- and project-manifest.

Please look at commit messages for details.

### CODE REVIEW

**Comment by ComradeVanti** [comment]
I'll fix the merge at some point today.

**Comment by favoyang** [comment]
The intention is good. However, I feel a little confused because the "Unity" prefix gives me a hint of the client-side stuff.

How about,

src/types/package-manifest.ts (UnityPackageManifest, Sample) is the package.json inside the UPM package. Maybe we could name the file unity-package-manifest.ts

src/types/project-manifest.ts (UnityProjectManifest), is the Packages/manifest.json inside the Unity project. Maybe we could name the unity-project-manifest.ts

src/types/packument.ts is the package metadata fetched from the npm registry. To align it with [npm types](https://github.com/npm/types/blob/master/index.d.ts), remove the "Unity" prefix and rename UnityPackument => Packument, UnityPackumentVersion => PackumentVersion.

Thought?

**Comment by ComradeVanti** [comment]
> src/types/package-manifest.ts (UnityPackageManifest, Sample) is the package.json inside the UPM package. Maybe we could name the file unity-package-manifest.ts
> src/types/project-manifest.ts (UnityProjectManifest), is the Packages/manifest.json inside the Unity project. Maybe we could name the unity-project-manifest.ts

If I undertand correctly, you want to prefix "unity-" to  the file-names correct? Sure, we can do that, just thought it would be too long haha.

> src/types/packument.ts is the package metadata fetched from the npm registry. To align it with [npm types](https://github.com/npm/types/blob/master/index.d.ts), remove the "Unity" prefix and rename UnityPackument => Packument, UnityPackumentVersion => PackumentVersion.

I would keep the Unity-prefix here, because we already have the `Packument` and `PackumentVersion` types in the project, from the `npm/types` package. These refer to actual npm packuments. Unity packuments have some slight differences as far as I can tell (such as having the underscores in front of some properties)

**Comment by ComradeVanti** [comment]
> These refer to actual npm packuments. Unity packuments have some slight differences as far as I can tell (such as having the underscores in front of some properties)

Oops my bad. Thats not true. It's jus the types in `npm/types` that are a little different and don't have the underscore.

But we still need a custom type here for another reason. The npm `PackumentVersion` type extends the npm `PackageJson` and thus has npm relevant properties, such as `scripts`. It is also missing unity relevant properties, such as `unity`. And since `UnityPackumentVersion` is different for Unity packages, `UnityPackument` is also different, because it needs to have `UnityPackumentVersion`s for its `versions` property.

**Comment by favoyang** [comment]
Okay, consider the "Unity" prefix in type names means it's Unity-specific stuff, which could be the client side or the server side thing. Let's keep all file names as it is now.

(aka no need to change anything except fix the conflicts).

**Review by favoyang — APPROVED** [review]

**Pull request merged**
