### PR TITLE
misc: side-by-side tests

### PR DESCRIPTION
**Pull request by ComradeVanti**
Change project structure to have tests side-by-side with implementation files, instead of them being in a separate tests folder.

### CODE REVIEW

**Comment by ComradeVanti** [comment]
@favoyang any reasons against this? I just personally prefer it this way.

**Comment by favoyang** [comment]
> @favoyang any reasons against this? I just personally prefer it this way.

I assume the old way is easier to strip the test code from production.

**Comment by ComradeVanti** [comment]
> I assume the old way is easier to strip the test code from production.

Yes and no. It's fairly easy to only target implementation code by only adding the two index files to compilation. TSC will then auto-detect all dependencies. In that way it is pretty easy to only select implementation code for building.

However, since the test file are so close, it becomes a lot easier to import test code into implementation code by accident. This is something I did not consider, but you made me think of, with your comment.

So, I think I will not make this change.

**Comment by favoyang** [comment]
Sounds good.

**Pull request closed without merging**
