### PR TITLE
Latest experimental changes

### PR DESCRIPTION
**Pull request by ComradeVanti**
This is a batch of experimental project structure changes. They mostly concern themselves with Dependency Injection (See #391).

The goal was to separate the app into the following parts:

- Domain: Pure logic. Does not "do" anything. Functional. No dependencies, no mocking. Can be easily Unit tested.
- IO: Code for interacting with external systems, like the fs or network. Contains only very little business logic. All impure. Needs mocking for integration testing.
- App: Application layer. Composes IO and Domain functions into imperative workflows. Has IO functions injected. Can be tested through integration tests with mocked IO or through e2e by using workflows in CLI layer. UI agnostic, could be used in a theoretical GUI version of openupm.
- CLI: Contains CLI specific logic. Tested through e2e tests. Pure CLI utilities can also be unit tested.

So the dependency graph for the whole project is

```mermaid
graph TD
    CLI --> App
    App --> IO
    App --> Domain
    IO --> Domain
```

### CODE REVIEW

**Comment by ComradeVanti** [comment]
@favoyang Let me know what you think. I have been taking the project through a whole bunch of architecture changes to determine what fits best and I think (and hope) I have landed on a good thing here. Hopefully no more large scale changes after this (except maybe migrating to oclif)

**Comment by favoyang** [comment]
As with any architect decisions, there are trade-offs. Sometimes, certain components end up taking on more responsibility and become the fat part. For instance, the lines between the CLI layer and the application layer, or what might be called a 'controller,' can become blurred.

I don't see much of dependency injection here, but in terms of code structure, this change seems to improve readability and testability. I'm okay with it.

**Review by favoyang — APPROVED** [review]

**Comment by favoyang** [comment]
Q: why [src/app/npmrc-io.ts](https://github.com/openupm/openupm-cli/pull/394/files#diff-a321717206e04269204dce481a3c3ae506a01795d93c942dc92402bbcc28b309) is an `app` instead of `io`?

**Comment by ComradeVanti** [comment]
> I don't see much of dependency injection here

Look for example in `remove-dependencies.ts`. See how IO functions like `readTextFile` are injected as a function argument. It's [functional dependency injection](https://blog.ploeh.dk/2017/01/30/partial-application-is-dependency-injection/).

> Q: why [src/app/npmrc-io.ts](https://github.com/openupm/openupm-cli/pull/394/files#diff-a321717206e04269204dce481a3c3ae506a01795d93c942dc92402bbcc28b309) is an app instead of io?

Yes, this is a slight oversight. Will fix now. Basically, all of the io modules which do not hide an external dependency should be in `app`. For example `npmrc-io` and `upm-config-io`. These modules use external IO, but only through injection so they should be in app. I will also maybe rename the files to make it clearer that they are not "direct" io.

**Comment by favoyang** [comment]
> Look for example in `remove-dependencies.ts`. See how IO functions like `readTextFile` are injected as a function argument. It's [functional dependency injection](https://blog.ploeh.dk/2017/01/30/partial-application-is-dependency-injection/).

I kind like this functional dependency injection approach - without needing to manage dependencies through a more structured but bloated DI framework.

**Pull request merged**
