### PR TITLE
refactor: disambiguate constructors

### PR DESCRIPTION
**Pull request by ComradeVanti**
Currently the names of constructor functions often conflict with variable names. For example the constructor function for `ScopedRegistry` is called `scopedRegistry`. Often you would also like to call a variable of type `ScopedRegistry` `scopedRegistry`. Then there is a name-conflict. This is also true for other types/constructors.

In order to fix this issue `make` was prefixed to all constructor functions, i.e. `makeScopedRegistry`.

Another option would have been to capitalize constructor functions, i.e. `ScopedRegistry`, but that would conflict with the type name.

### CODE REVIEW

**Comment by ComradeVanti** [comment]
Also, also we could introduce classes for custom types and use actual constructors. But something feels wrong about using a class for what are essentially aliases of simple values. Like `PackageReference` is essentially a `string` and it feels off to wrap that in an object.

**Review by favoyang — CHANGES_REQUESTED** [review]
I slightly prefer using `createStuff` than `makeStuff`. But it's okay.

Merge conflicts need to be resolved though.

**Comment by ComradeVanti** [comment]
I have no issue with the `create` wording. I did not change it now in this PR, but if you want I can open another one where I change it to `create` everywhere. Just let me know.

**Comment by favoyang** [comment]
> I have no issue with the `create` wording. I did not change it now in this PR, but if you want I can open another one where I change it to `create` everywhere. Just let me know.

Let's keep `make` then, as long as we keep it consistent.

**Review by favoyang — CHANGES_REQUESTED** [review]
Merge conflicts need to be resolved.

**Review by favoyang — APPROVED** [review]

**Pull request merged**
