### PR TITLE
test: add-command e2e tests

### PR DESCRIPTION
**Pull request by ComradeVanti**
This PR adds some e2e tests for the add command.

### CODE REVIEW

**Comment by ComradeVanti** [comment]
@favoyang opinions on this approach?

**Comment by ComradeVanti** [comment]
Are there any other important scenarios we should test for this command?

**Comment by favoyang** [comment]
> @favoyang opinions on this approach?
> Are there any other important scenarios we should test for this command?

LGTM.

Because you hardcoded version 2021.3.36f1 in the project setup script, is it necessary to add an assertion here to ensure the environment (Unity installation version) is ready?

**Review by favoyang — APPROVED** [review]

**Comment by ComradeVanti** [comment]
> Because you hardcoded version 2021.3.36f1 in the project setup script, is it necessary to add an assertion here to ensure the environment (Unity installation version) is ready?

This is the same version that is hardcoded in the e2e docker images. If the version that is on the image changes then tests will fail, if they are not adjusted.

**Pull request merged**
